/*
 * SPDX-FileCopyrightText: 2026 Icaro2M
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include <cstdint>
#include <limits>

namespace locus::application {

    /**
     * @brief Raw storage type used by application document identifiers.
     */
    using DocumentIdValue = std::uint64_t;

    /**
     * @brief Sentinel value representing an invalid document identifier.
     */
    inline constexpr DocumentIdValue InvalidDocumentIdValue =
        std::numeric_limits<DocumentIdValue>::max();

    /**
     * @brief Stable identifier for an open document session.
     */
    struct DocumentId {
        /**
         * @brief Raw identifier value.
         */
        DocumentIdValue value = InvalidDocumentIdValue;

        /**
         * @brief Creates an invalid document identifier.
         */
        constexpr DocumentId() = default;

        /**
         * @brief Creates a document identifier from a raw value.
         *
         * Production identifiers are generated by DocumentManager.
         *
         * @param value Raw identifier value.
         */
        constexpr explicit DocumentId(DocumentIdValue value)
            : value(value)
        {
        }

        /**
         * @brief Checks whether this identifier references a document.
         *
         * @return True when the identifier is valid.
         */
        [[nodiscard]] constexpr bool is_valid() const noexcept
        {
            return value != InvalidDocumentIdValue;
        }

        /**
         * @brief Checks whether this identifier is invalid.
         *
         * @return True when the identifier is invalid.
         */
        [[nodiscard]] constexpr bool is_invalid() const noexcept
        {
            return !is_valid();
        }

        /**
         * @brief Compares two document identifiers for equality.
         *
         * @param lhs Left-hand identifier.
         * @param rhs Right-hand identifier.
         * @return True when both identifiers store the same value.
         */
        friend constexpr bool operator==(
            DocumentId lhs,
            DocumentId rhs) noexcept
        {
            return lhs.value == rhs.value;
        }

        /**
         * @brief Compares two document identifiers for inequality.
         *
         * @param lhs Left-hand identifier.
         * @param rhs Right-hand identifier.
         * @return True when the identifiers store different values.
         */
        friend constexpr bool operator!=(
            DocumentId lhs,
            DocumentId rhs) noexcept
        {
            return !(lhs == rhs);
        }
    };

} // namespace locus::application
