/*
 * SPDX-FileCopyrightText: 2026 Icaro2M
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include "editor/render/RenderAdapterTypes.h"
#include "editor/scene/SceneNodeId.h"
#include "graphics/common/GraphicsResult.h"
#include "graphics/mesh/MeshRenderCache.h"
#include "graphics/mesh/MeshUploadData.h"
#include "graphics/mesh/MeshUploader.h"
#include "graphics/scene/RenderLayer.h"
#include "graphics/scene/RenderObject.h"

#include <string>

namespace locus::editor {

    class MeshNode;

    /**
     * @brief Options used when converting an editor mesh node to render data.
     */
    struct MeshNodeRenderOptions {
        /**
         * @brief Upload conversion options used after kernel triangulation.
         */
        RenderMeshUploadOptions uploadOptions{};

        /**
         * @brief Logical layer assigned to generated render objects.
         */
        graphics::RenderLayer layer = graphics::RenderLayer::Default;

        /**
         * @brief Fallback shader used by the render object.
         */
        const graphics::Shader* shader = nullptr;

        /**
         * @brief Optional material used by the render object.
         */
        const graphics::VisualMaterialInstance* material = nullptr;

        /**
         * @brief True when the render object should be flagged as selected.
         */
        bool selected = false;

        /**
         * @brief True when the render object should be flagged as hovered.
         */
        bool hovered = false;

        /**
         * @brief True when the render object should be drawn as wireframe.
         */
        bool wireframe = false;

        /**
         * @brief True when empty meshes should still produce diagnostics instead of being silently skipped.
         */
        bool reportEmptyMeshes = true;
    };

    /**
     * @brief Diagnostics produced when converting a mesh node to render data.
     */
    struct MeshNodeRenderResult {
        /**
         * @brief Source editor node identifier.
         */
        SceneNodeId nodeId{};

        /**
         * @brief Cache key used for GPU mesh lookup or upload.
         */
        graphics::MeshRenderCacheKey cacheKey{};

        /**
         * @brief Statistics generated by RenderMeshUploadAdapter.
         */
        RenderMeshUploadResult uploadResult{};

        /**
         * @brief True when kernel triangulation produced triangle upload data.
         */
        bool hasUploadData = false;

        /**
         * @brief True when a GPU mesh was found or uploaded through the cache.
         */
        bool hasGpuMesh = false;

        /**
         * @brief True when a render object was produced.
         */
        bool hasRenderObject = false;

        /**
         * @brief True when the mesh node was intentionally skipped.
         */
        bool skipped = false;

        /**
         * @brief Human-readable diagnostic message.
         */
        std::string message;
    };

    /**
     * @brief Converts editor mesh nodes into graphics render payloads.
     *
     * MeshNodeRenderAdapter is an integration layer. It asks the kernel to produce
     * render-ready triangle data, converts it to graphics upload data, and optionally
     * resolves a cached GPU mesh for RenderObject creation.
     */
    class MeshNodeRenderAdapter {
    public:
        /**
         * @brief Builds triangle upload data from a mesh node.
         *
         * @param node Source mesh node.
         * @param options Conversion options.
         * @param result Optional diagnostic output.
         * @return CPU-side mesh upload payload.
         */
        [[nodiscard]] static graphics::MeshUploadData build_upload_data(
            const MeshNode& node,
            const MeshNodeRenderOptions& options = {},
            MeshNodeRenderResult* result = nullptr
        );

        /**
         * @brief Builds a render object from an already resolved GPU mesh.
         *
         * @param node Source mesh node.
         * @param gpuMesh GPU mesh owned elsewhere, usually by MeshRenderCache.
         * @param options Render object options.
         * @return Render object referencing the supplied GPU mesh.
         */
        [[nodiscard]] static graphics::RenderObject build_render_object(
            const MeshNode& node,
            const graphics::GpuMesh* gpuMesh,
            const MeshNodeRenderOptions& options = {}
        );

        /**
         * @brief Builds a render object backed by MeshRenderCache.
         *
         * @param node Source mesh node.
         * @param meshRevision Revision used to invalidate stale cached GPU meshes.
         * @param cache Mesh cache that owns generated GPU resources.
         * @param uploader GPU uploader used when the cache misses.
         * @param options Render object options.
         * @param result Optional diagnostic output.
         * @return Render object on success, or graphics error on failure.
         */
        [[nodiscard]] static graphics::GraphicsResult<graphics::RenderObject> build_cached_render_object(
            const MeshNode& node,
            graphics::u64 meshRevision,
            graphics::MeshRenderCache& cache,
            const graphics::MeshUploader& uploader,
            const MeshNodeRenderOptions& options = {},
            MeshNodeRenderResult* result = nullptr
        );

        /**
         * @brief Builds the cache key used by this adapter for a mesh node.
         *
         * @param node Source mesh node.
         * @param meshRevision Revision used to invalidate stale cached GPU meshes.
         * @return Mesh render cache key.
         */
        [[nodiscard]] static graphics::MeshRenderCacheKey build_cache_key(
            const MeshNode& node,
            graphics::u64 meshRevision
        );

    private:
        /**
         * @brief Copies editor transform data to graphics transform data.
         *
         * @param node Source scene node.
         * @return Render transform.
         */
        [[nodiscard]] static graphics::RenderTransform build_render_transform(const MeshNode& node);

        /**
         * @brief Copies editor visibility metadata to graphics visibility data.
         *
         * @param node Source scene node.
         * @return Render visibility flags.
         */
        [[nodiscard]] static graphics::RenderVisibility build_render_visibility(const MeshNode& node);

        /**
         * @brief Writes a diagnostic message to an optional result object.
         *
         * @param result Optional result object.
         * @param message Message to write.
         */
        static void set_message(MeshNodeRenderResult* result, std::string message);
    };

} // namespace locus::editor